using SpectraEngine.Core;

namespace SpectraEngine.Graphics;

/// <summary>
/// Replica of <c>acr</c> (RenderBlocks) — client-side block geometry dispatcher.
/// Dispatches rendering to per-render-type methods based on <see cref="Block.GetRenderType"/>.
///
/// All per-type render methods are stubs; actual geometry is generated by the
/// Raylib rendering subsystem which calls into this class.
///
/// Source spec: Documentation/VoxelCore/Parity/Specs/Rendering_BlockModel_Spec.md
/// </summary>
public sealed class RenderBlocks
{
    // ── Tile Entity Special Renderers (TESR) (spec §9) ────────────────────────
    // Chest (54), EnchantmentTable (116), Sign (63/68) use TESR paths.
    public static readonly int[] TesrBlockIds = [54, 116, 63, 68];

    // ── Dispatch (spec §2) ────────────────────────────────────────────────────

    /// <summary>
    /// Main render dispatch. Calls the appropriate render method for the block.
    /// Returns true if the block was rendered, false if unrecognised type.
    /// Spec: <c>acr.b(yy block, int x, int y, int z)</c>.
    /// </summary>
    public bool RenderBlock(Block block, int x, int y, int z)
    {
        return block.GetRenderType() switch
        {
            0  => RenderFullCube(block, x, y, z),
            1  => RenderCrossSprite(block, x, y, z),
            2  => RenderTorch(block, x, y, z),
            3  => RenderFire(block, x, y, z),
            4  => RenderFluid(block, x, y, z),
            5  => RenderRedstoneWire(block, x, y, z),
            6  => RenderCrops(block, x, y, z),
            7  => RenderDoor(block, x, y, z),
            8  => RenderLadder(block, x, y, z),
            9  => RenderRail(block, x, y, z),
            10 => RenderStairs(block, x, y, z),
            11 => RenderFence(block, x, y, z),
            12 => RenderLever(block, x, y, z),
            13 => RenderCactus(block, x, y, z),
            14 => RenderBed(block, x, y, z),
            15 => RenderVine(block, x, y, z),
            16 => RenderRepeater(block, x, y, z, powered: false),
            17 => RenderRepeater(block, x, y, z, powered: true),
            18 => RenderPane(block, x, y, z),
            19 => RenderLilypad(block, x, y, z),
            20 => RenderCauldron(block, x, y, z),
            21 => RenderFenceGate(block, x, y, z),
            23 => RenderDragonEgg(block, x, y, z),
            24 => RenderCocoaPod(block, x, y, z),
            25 => RenderEndPortalFrame(block, x, y, z),
            26 => RenderSlabExtended(block, x, y, z),
            27 => RenderRailVariant(block, x, y, z),
            _  => false
        };
    }

    // ── Per-type render stubs (spec §3 table) ─────────────────────────────────
    // Each method is a stub. Actual Raylib tessellation is wired in by the renderer.

    /// <summary>Type 0 — full opaque cube; 6 axis-aligned faces with occlusion culling.</summary>
    private bool RenderFullCube(Block block, int x, int y, int z) => true;

    /// <summary>Type 1 — cross / X sprite; two quads at 45°; double-sided, no culling.</summary>
    private bool RenderCrossSprite(Block block, int x, int y, int z) => true;

    /// <summary>Type 2 — torch; upright or leaning 4 directions based on metadata.</summary>
    private bool RenderTorch(Block block, int x, int y, int z) => true;

    /// <summary>Type 3 — fire; multi-face animated quads on adjacent solid faces.</summary>
    private bool RenderFire(Block block, int x, int y, int z) => true;

    /// <summary>Type 4 — fluid; variable-height top face + skewed side faces.</summary>
    private bool RenderFluid(Block block, int x, int y, int z) => true;

    /// <summary>Type 5 — redstone wire; flat quads with 4 connection arms; signal-strength colour.</summary>
    private bool RenderRedstoneWire(Block block, int x, int y, int z) => true;

    /// <summary>Type 6 — crops; hash-pattern (#) of 4 quads per block.</summary>
    private bool RenderCrops(Block block, int x, int y, int z) => true;

    /// <summary>Type 7 — door; 3/16-thick panel with UV rotation per facing/open state.</summary>
    private bool RenderDoor(Block block, int x, int y, int z) => true;

    /// <summary>Type 8 — ladder; flat face quad pressed against wall.</summary>
    private bool RenderLadder(Block block, int x, int y, int z) => true;

    /// <summary>Type 9 — rail; flat ground quad; curved variant from metadata.</summary>
    private bool RenderRail(Block block, int x, int y, int z) => true;

    /// <summary>Type 10 — stairs; lower half + back upper quarter (two AABB slabs).</summary>
    private bool RenderStairs(Block block, int x, int y, int z) => true;

    /// <summary>Type 11 — fence; post core + dynamic arms toward adjacent fences/blocks.</summary>
    private bool RenderFence(Block block, int x, int y, int z) => true;

    /// <summary>Type 12 — lever; stick + cobblestone base; 2 orientations.</summary>
    private bool RenderLever(Block block, int x, int y, int z) => true;

    /// <summary>Type 13 — cactus; inset faces (2/16 gap on all sides).</summary>
    private bool RenderCactus(Block block, int x, int y, int z) => true;

    /// <summary>Type 14 — bed; two-piece low (9/16 tall) with foot/head orientation.</summary>
    private bool RenderBed(Block block, int x, int y, int z) => true;

    /// <summary>Type 15 — vine; flat quads on each attached wall face (N/S/E/W/top).</summary>
    private bool RenderVine(Block block, int x, int y, int z) => true;

    /// <summary>Types 16/17 — redstone repeater; flat base + two mini-torches.</summary>
    private bool RenderRepeater(Block block, int x, int y, int z, bool powered) => true;

    /// <summary>Type 18 — glass pane / iron bars; 2/16-thick post + arms.</summary>
    private bool RenderPane(Block block, int x, int y, int z) => true;

    /// <summary>Type 19 — lilypad; flat 1/64 quad slightly above water surface.</summary>
    private bool RenderLilypad(Block block, int x, int y, int z) => true;

    /// <summary>Type 20 — cauldron; hollow vessel with outer walls + inner cavity.</summary>
    private bool RenderCauldron(Block block, int x, int y, int z) => true;

    /// <summary>Type 21 — fence gate; two pillar posts + thin centre panel (open or closed).</summary>
    private bool RenderFenceGate(Block block, int x, int y, int z) => true;

    /// <summary>Type 23 — dragon egg; stepped pyramid of decreasing cubes.</summary>
    private bool RenderDragonEgg(Block block, int x, int y, int z) => true;

    /// <summary>Type 24 — cocoa pod; curved bump on log face, 3 size stages.</summary>
    private bool RenderCocoaPod(Block block, int x, int y, int z) => true;

    /// <summary>Type 25 — end portal frame; flat base (0.875 tall) + optional eye.</summary>
    private bool RenderEndPortalFrame(Block block, int x, int y, int z) => true;

    /// <summary>Type 26 — slab with extended piece; enchantment table.</summary>
    private bool RenderSlabExtended(Block block, int x, int y, int z) => true;

    /// <summary>Type 27 — rail variant (powered/detector rail geometry).</summary>
    private bool RenderRailVariant(Block block, int x, int y, int z) => true;

    // ── Light multipliers per face (spec §4) ─────────────────────────────────

    /// <summary>
    /// Vanilla AO-style face brightness multipliers.
    /// Top=1.0, Bottom=0.5, N/S=0.8, E/W=0.6.
    /// Spec: Rendering_BlockModel_Spec.md §4.
    /// </summary>
    public static float GetFaceBrightness(int face) => face switch
    {
        0 => 0.5f,  // bottom
        1 => 1.0f,  // top
        2 => 0.8f,  // north
        3 => 0.8f,  // south
        4 => 0.6f,  // west
        5 => 0.6f,  // east
        _ => 1.0f
    };
}
