namespace SpectraEngine.Core.Mods;

/// <summary>
/// Entry point every mod plugin must implement.
/// Generated by ModTranspiler as &lt;ModName&gt;Plugin.cs.
/// Loaded at runtime via AssemblyLoadContext.
/// </summary>
public interface ISpectraMod
{
    string ModId      { get; }
    string DisplayName { get; }
    string Version    { get; }

    void OnLoad(IEngine engine);
    void OnUnload();
}
