using SpectraSharp.ModTranspiler.Model;
using SpectraSharp.ModTranspiler.Pipeline;

namespace SpectraSharp.ModTranspiler.Templates;

static class BlockTemplate
{
    public static (string File, string Source) Emit(string modName, BlockDescriptor block)
    {
        string ns   = $"SpectraSharp.Bridge.Mods.{Safe(modName)}";
        string cls  = Safe(block.ClassName);
        string hard = block.Hardness.ToString("F1", System.Globalization.CultureInfo.InvariantCulture);
        string res  = block.BlastResistance.ToString("F1", System.Globalization.CultureInfo.InvariantCulture);

        string tickBody = TranslateMethod(block, "updateTick")
                       ?? TranslateMethod(block, "randomDisplayTick")
                       ?? "        // No tick logic";
        string useBody  = TranslateMethod(block, "onBlockActivated") ?? "        return false;";
        string dropBody = BuildDropBody(block);

        string source = $$"""
            // Auto-generated by SpectraSharp ModTranspiler
            using SpectraSharp.Bridge.Overrides;
            using SpectraSharp.Core.Mods;

            namespace {{ns}};

            sealed class {{cls}} : BlockBase
            {
                public override int    BlockId          => {{block.BlockId}};
                public override string JavaClassName    => "{{modName}}.{{block.ClassName}}";
                public override int    TextureIndex     => {{block.TextureIndex}};
                protected override float Hardness        => {{hard}}f;
                protected override float BlastResistance => {{res}}f;

                protected override void BlockTick(double deltaSeconds)
                {
            {{tickBody}}
                }

                public override bool OnUse(IWorld world, object player, int x, int y, int z, Face face)
                {
            {{useBody}}
                }

                public override IEnumerable<ItemStack> GetDrops(int meta, Random rng)
                {
            {{dropBody}}
                }
            }
            """;

        return ($"Blocks/{cls}.cs", source);
    }

    static string? TranslateMethod(BlockDescriptor block, string javaName)
    {
        var method = block.Methods.FirstOrDefault(m => m.Name == javaName);
        return method == null ? null : Translator.TranslateBody(method.JavaLines);
    }

    static string BuildDropBody(BlockDescriptor block)
    {
        var idDropped = block.Methods.FirstOrDefault(m => m.Name == "idDropped");
        return idDropped != null
            ? $"        yield return new ItemStack(/* TODO: translate idDropped */ {block.BlockId}, 1);"
            : $"        yield return new ItemStack({block.BlockId}, 1);";
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
