using SpectraEngine.ModTranspiler.Model;

namespace SpectraEngine.ModTranspiler.Templates;

static class EntryPointTemplate
{
    public static (string File, string Source) Emit(ModManifest manifest)
    {
        string ns  = $"SpectraEngine.Bridge.Mods.{Safe(manifest.ModName)}";
        string cls = Safe(manifest.ModName) + "Plugin";
        string id  = manifest.ModName.ToLowerInvariant();

        var regs = new System.Text.StringBuilder();
        foreach (var b in manifest.NewBlocks)
            regs.AppendLine($"        engine.Registry.RegisterBlock({b.BlockId}, new {Safe(b.ClassName)}());");
        foreach (var i in manifest.NewItems)
            regs.AppendLine($"        engine.Registry.RegisterItem({i.ItemId}, new {Safe(i.ClassName)}());");
        foreach (var w in manifest.WorldGenHooks)
            regs.AppendLine($"        engine.Registry.RegisterWorldGenHook(new {Safe(w.ClassName)}WorldGen());");

        string source = $$"""
            // Auto-generated by SpectraEngine ModTranspiler
            using SpectraEngine.Core.Mods;
            using HarmonyLib;

            namespace {{ns}};

            public sealed class {{cls}} : ISpectraMod
            {
                public string ModId       => "{{id}}";
                public string DisplayName => "{{manifest.ModName}}";
                public string Version     => "1.0";

                public void OnLoad(IEngine engine)
                {
            {{regs}}
                    var harmony = new Harmony($"SpectraEngine.mod.{{id}}");
                    harmony.PatchAll(GetType().Assembly);
                }

                public void OnUnload() { }
            }
            """;

        return ($"{cls}.cs", source);
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
