using SpectraSharp.ModTranspiler.Model;
using SpectraSharp.ModTranspiler.Pipeline;

namespace SpectraSharp.ModTranspiler.Templates;

static class HookTemplate
{
    public static (string File, string Source) Emit(string modName, InjectionDescriptor hook)
    {
        string ns        = $"SpectraSharp.Bridge.Mods.{Safe(modName)}";
        string hookClass = $"{Safe(hook.TargetClassCs)}_{Safe(hook.TargetMethodCs)}_Hook";
        string attr      = hook.Position switch
        {
            InjectionPosition.Prepend     => "HarmonyPrefix",
            InjectionPosition.Append      => "HarmonyPostfix",
            InjectionPosition.ReplaceBody => "HarmonyTranspiler",
            _                             => "HarmonyPostfix",
        };
        string returnType = hook.Position == InjectionPosition.Prepend ? "bool" : "void";
        string returnLine = hook.Position == InjectionPosition.Prepend
            ? "\n            return true; // true = continue to original method"
            : "";

        string body = Translator.TranslateBody(hook.JavaLines);

        string source = $$"""
            // Auto-generated by SpectraSharp ModTranspiler
            using HarmonyLib;
            using SpectraSharp.Core;

            namespace {{ns}};

            [HarmonyPatch(typeof({{hook.TargetClassCs}}), nameof({{hook.TargetClassCs}}.{{hook.TargetMethodCs}}))]
            static class {{hookClass}}
            {
                [{{attr}}]
                static {{returnType}} {{hook.Position}}({{hook.TargetClassCs}} __instance)
                {
            {{body}}{{returnLine}}
                }
            }
            """;

        return ($"Hooks/{hookClass}.cs", source);
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
