using SpectraEngine.ModTranspiler.Model;
using SpectraEngine.ModTranspiler.Pipeline;

namespace SpectraEngine.ModTranspiler.Templates;

static class ItemTemplate
{
    public static (string File, string Source) Emit(string modName, ItemDescriptor item)
    {
        string ns  = $"SpectraEngine.Bridge.Mods.{Safe(modName)}";
        string cls = Safe(item.ClassName);
        string atk = item.AttackDamage.ToString("F1", System.Globalization.CultureInfo.InvariantCulture);

        string useBody = TranslateMethod(item, "onItemUse")
                      ?? TranslateMethod(item, "onItemUseFirst")
                      ?? "        return false;";

        string source = $$"""
            // Auto-generated by SpectraEngine ModTranspiler
            using SpectraEngine.Core.Mods;
            using IWorld = SpectraEngine.Core.IWorld;

            namespace {{ns}};

            sealed class {{cls}} : ItemBase
            {
                public override int    ItemId           => {{item.ItemId}};
                public override string JavaClassName    => "{{modName}}.{{item.ClassName}}";
                public override int    ItemTextureIndex => {{item.TextureIndex}};
                public override int    MaxStackSize     => {{item.MaxStackSize}};
                public override int    MaxDamage        => {{item.MaxDamage}};
                public override float  GetAttackDamage() => {{atk}}f;

                public override bool OnUseOnBlock(
                    IWorld world, int x, int y, int z, Face face, ItemStack stack)
                {
            {{useBody}}
                }
            }
            """;

        return ($"Items/{cls}.cs", source);
    }

    static string? TranslateMethod(ItemDescriptor item, string javaName)
    {
        var method = item.Methods.FirstOrDefault(m => m.Name == javaName);
        return method == null ? null : Translator.TranslateBody(method.JavaLines);
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
