using SpectraSharp.ModTranspiler.Model;
using System.Collections.Generic;

namespace SpectraSharp.ModTranspiler.Templates;

static class RecipeTemplate
{
    public static (string File, string Source) Emit(string modName, List<RecipeDescriptor> recipes)
    {
        string ns  = $"SpectraSharp.Bridge.Mods.{Safe(modName)}";
        string cls = $"{Safe(modName)}Recipes";

        var body = new System.Text.StringBuilder();
        foreach (var r in recipes)
            body.AppendLine(EmitRecipe(r));

        string source = $$"""
            // Auto-generated by SpectraSharp ModTranspiler
            using System.Collections.Generic;
            using SpectraSharp.Core.Mods;

            namespace {{ns}};

            static class {{cls}}
            {
                public static void Register(ICraftingManager crafting, ISmeltingManager smelting)
                {
            {{body}}
                }
            }
            """;

        return ($"Recipes/{cls}.cs", source);
    }

    static string EmitRecipe(RecipeDescriptor r)
    {
        string xp = r.SmeltXp.ToString("F2", System.Globalization.CultureInfo.InvariantCulture);
        string ids = string.Join(", ", r.ShapelessIds);

        return r.Type switch
        {
            RecipeType.Smelting => $"""
                    smelting.AddSmeltingRecipe(
                        inputId: {r.SmeltInputId},
                        output: new ItemStack({r.OutputId}, 1),
                        xp: {xp}f);
            """,
            RecipeType.Shapeless => $$"""
                    crafting.AddShapelessRecipe(
                        output: new ItemStack({{r.OutputId}}, {{r.OutputCount}}),
                        ingredients: new[] { {{ids}} });
            """,
            RecipeType.Shaped when r.Pattern.Length > 0 => EmitShaped(r),
            _ => $"        // TODO: MANUAL REVIEW REQUIRED — shaped recipe for item {r.OutputId}",
        };
    }

    static string EmitShaped(RecipeDescriptor r)
    {
        // Build pattern literal: new[] { "###", "# #", "###" }
        string patternLiteral = "new[] { " +
            string.Join(", ", r.Pattern.Select(row => $"\"{row}\"")) +
            " }";

        // Build key literal: new Dictionary<char, int> { ['#'] = 4, ['S'] = 280 }
        string keyEntries = string.Join(", ",
            r.Ingredients.Select(kv => $"['{kv.Key}'] = {kv.Value}"));
        string keyLiteral = $"new Dictionary<char, int> {{ {keyEntries} }}";

        return $"""
                crafting.AddShapedRecipe(
                    output: new ItemStack({r.OutputId}, {r.OutputCount}),
                    pattern: {patternLiteral},
                    key: {keyLiteral});
        """;
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
