using SpectraSharp.ModTranspiler.Model;
using SpectraSharp.ModTranspiler.Pipeline;

namespace SpectraSharp.ModTranspiler.Templates;

static class WorldGenTemplate
{
    public static (string File, string Source) Emit(string modName, WorldGenDescriptor wg)
    {
        string ns    = $"SpectraSharp.Bridge.Mods.{Safe(modName)}";
        string cls   = Safe(wg.ClassName) + "WorldGen";
        string body  = Translator.TranslateBody(wg.JavaLines);

        // Emit captured instance fields (e.g. vein count, ore count) with their default values
        var fieldsBuilder = new System.Text.StringBuilder();
        foreach (var (name, value) in wg.Fields)
            fieldsBuilder.AppendLine($"    int {name} = {value};");
        string fields = fieldsBuilder.ToString();

        string source = $$"""
            // Auto-generated by SpectraSharp ModTranspiler
            #pragma warning disable CS0414 // field assigned but never used — captured from Java
            using System;
            using SpectraSharp.Core;
            using SpectraSharp.Core.Mods;

            namespace {{ns}};

            sealed class {{cls}} : IWorldGenHook
            {
            {{fields}}
                public void OnPopulateChunk(IWorld world, Random rng, int chunkX, int chunkZ)
                {
            {{body}}
                }
            }
            """;

        return ($"WorldGen/{cls}.cs", source);
    }

    static string Safe(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));
}
